### ISSUE TITLE
Guild Roster Window bugged again (on order)

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1438]
shows 1/1 and no other members when logging in. After /rel its goes back to normal. Bug was already fixed, now back again after last hotfix.

**Comment by Tiggonos** [comment]
fixed as of 25.09.15

**Comment by Tiggonos** [comment]
and again broken.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/7305

>- Once you log in and hit G>Roster> This happens.

> **Only way to fix it is to /rel**
![maxeras_000](https://cloud.githubusercontent.com/assets/16864486/17833434/d40d47da-6725-11e6-821b-3a73392b5a1b.jpg)

**Comment by Kaberu** [comment]
Hello,
Three days ago this bug began effecting me also.  I can only see myself in guild.  My guild mate is experiencing the same issue.
Thank you for the assistance.

**Comment by Kylashandra** [comment]
Same Issue for my guild, Stress Test, on Order side. No member showing in roster window (not even me), /rel doesn't fix it.

**Comment by Spelldaoc** [comment]
Guild roster issue still persists showing 1/1 when other members are online.

**Comment by xpander69** [comment]
related? https://github.com/WarEmu/WarBugs/issues/20481
in that case 400 members in guild caused the issue. 399 was working fine.
