### ISSUE TITLE
[Bright Wizard] [Rain of Fire] + [Scorched Earth] or [Flame Breath]

### ISSUE THREAD

**Issue by dgoyachev** [WarEmu/WarBugs#1481]
Looks like if SE casted while RoF, it does not interrupt latter but acting simultaneously and does not consume any combustion. Amazing amount of AOE damage. Same issue with Flame Breath under RoF, in this case combustion does not increasing.

**Comment by milosxe** [comment]
https://github.com/WarEmu/WarBugs/issues/1413
Is it fixed now?

**Comment by dgoyachev** [comment]
In my case moving always interrupts RoF. What related simultaneous casting - it does not reproduces immediately, only after few RoFs, with peculiar animation bug - character starts moving wry, as if casting still continues.

**Comment by ozarmidrashim** [comment]
Seems to be a visual bug - client expects that casts can interrupt channels. The emulator's handling has been changed to match this.
