### ISSUE TITLE
[OIL] [KEEP] [ORVR] Line of sight troubles in some keeps

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15675]
**Expected behavior and actual behavior:**

As requested here: https://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=35231&p=390411#p390414

Keeps which oil can't be reliably reached:
* Praag: Southern Garrison outer oil https://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=33350&p=375535&hilit=Southern+Garrison#p375535
* Thunder Mountain: Karak Karag outter oil https://github.com/WarEmu/WarBugs/issues/14355
* Black Crag: Badmoon Hole outter oil.
* Black Fire Pass: Gnol Baraz outter oil.

There are other keeps that, while not being so restrictive, still seem to have issues with line of sight, with some skills not being able to be performed in range:
* Reikland: Wilhelm's Fist outter oil. Seems to be impossible to hit from the main ramp at some distance. Can be hit properly at normal range and from both sides of the ramp. Annoying, but far from game breaking.
* Avelorn: Ghrond's Sacristy outter oil. Seems also to be hard to hit from the ramp in both sides of the main gate. Even less annoying than the above one. Barely noticeable unless that you are specifically searching for weak spots.
* Talabecland: Passwatch Castle inner oil. Some line of sight issues due to scenography.

Keeps with blind spots where doesn't seem normal that you can't see it:
* Saphery: Well of Qhaysh outter oil. Has two very small blind spots in the right side. You can hit it from any other location around them.
* Talabecland: Passwatch Castle outter oil. Blind spot in the right, blind small zone in the left.

This issue seems to be only happening in keeps that have unusual inclinations or ramps in their main gates.

**Steps to reproduce the problem:**

Try to hit the oil spawned within range of your skills

**Testing Screenshots/Videos/Evidences (always needed):**

Some are currently in their own reports, and I will try to add more screenshots. Given the issue, anyone contributing with more screens/vids would be perfect, as long as screens can't be added without a zone ope, oil spawned, and people online aware of this. Thanks to all.

**Comment by Natherul** [comment]
addressed:
Praag: Southern Garrison outer
Thunder Mountain: Karak Karag outer
Black Crag: Badmoon Hole outer
Black Fire Pass: Gnol Baraz outer

**Comment by Ootootoo** [comment]
> addressed:
> Praag: Southern Garrison outer
> Thunder Mountain: Karak Karag outer
> Black Crag: Badmoon Hole outer
> Black Fire Pass: Gnol Baraz outer

The others are actually insignificant compared with those 4 major offenders. Thank you :)

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday

**Comment by RoR-Zomega** [comment]
Southern Garrison's outer oil is just as difficult to target with 100ft abilities as it was before the patch. Still requires jumping and instant-casts. This was tested with desto trying to hit the oil on a zero-star order keep.

Not sure if you want to re-open this report or if you want me to do a new one.

**Comment by Natherul** [comment]
southern garrison is still an issue, but not LOS anymore but more an issue of out of range. I have requested that this topic stay open until a good fix has been found but its no longer an issue of LOS

**Comment by RoR-Zomega** [comment]
Karak Karag (Thunder Mountain) also still having the same issue, transitioning from out of LOS to out of range and needing jumps to hit the oil.
