### ISSUE TITLE
Zone 0 and stuck there

### ISSUE THREAD

**Issue by Gotrek129** [WarEmu/WarBugs#3842]
Hello I was offline 2 days coz was on concert. Im comming back loging to RoR and my char is in "Zone 0" dead without any skill in skill book, without anythnik in bags and equipped on his self. I just got my lvl and my 44gold. I tryed use :
-stuck
-stuck x2
-unlock
-reload
everythink but im still bugged. Some gm teleported me to altdorf ur other places but i still havent my skills items in my inventory inventory and equipment. Some time when I was running on teleported location a had lag dc and when I loged back. ZONE 0! PLS help me. MY CHARS NAMES ARE GRUNDIM AND THORLOF

**Comment by vove-RoR** [comment]
For the sake of reference you could post URL of your forum topic where you attached some screenshots: http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=10830

You are not the only one in that problem but for everyone it got solved by writing /stuck, check some of the topics on forums, like this one: http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=171

**Comment by vove-RoR** [comment]
> Your issue should be fixed after the next server restart. Sorry for the inconvenience, and the time it took us to fix it.

Good for you!

**Comment by Gotrek129** [comment]
But when Is server restart?

**Comment by Gotrek129** [comment]
I logged on Grundim and he is stil in these situation ;_;

**Comment by Gotrek129** [comment]
Ok he isnt dead and he isnt in zone 0 but he still dont have his items and he still dont have skils and items equipped

**Comment by Gotrek129** [comment]
Ok i reloged and e is again these same like on start

**Comment by Gotrek129** [comment]
Yeah today I loged on Grundim and he is still in these same situation PLS HELP ME

**Comment by vove-RoR** [comment]
You have to wait for a server restart.

**Comment by Evildoor** [comment]
Work for GMs, so bugtracker is a wrong place for this.
