### ISSUE TITLE
Desperate Gambit Quest

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#6030]
Looks as completed but its not.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Soulwhisper** [comment]
Still bugged

**Comment by Simmox** [comment]
im not understanding the previous comments ,is the quest known to be broken?,i cant find the shrine and or the penitent knights and their commander?

**Comment by Tertilus** [comment]
Simmox the shrine can be found in West Praag, in a valley south of the PQ Screaming Daemons. You'll see a green questgiver dot pop next to it when you get close. Turning that step in though results in a dead end, as there is no follow-on quest given. I assume it is still broken.

**Comment by NorKalli** [comment]
Finally fixed

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
